apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app   
  template:
    metadata:
      labels:
        app: nginx-app  
    spec:
      containers:
        - name: nginx-app
          image: jaishankar7655/weatherforcastapplication-nginx:latest
          ports:
            - containerPort: 80
